### ISSUE TITLE
Got some error when start a Hexo server.

### ISSUE THREAD

**Issue by DonkeyBear** [jue89/hexo-theme-hyde#1]
When I clone this theme to my Hexo project and start a server with it, it got some error message that I can't figure out, take a look, please.
```
ERROR {
  err: TypeError: /Users/an/Documents/Hexo_project/test/themes/hyde/layout/layout.ejs:4
      2| <html lang="en-us">
      3| 
   >> 4|   <%- partial('_partial/head') %>
      5| 
      6|   <body class="<%- config.theme_class %>">
      7| 
  
  /Users/an/Documents/Hexo_project/test/themes/hyde/layout/_partial/head.ejs:18
      16| 
      17|   <!-- Icons -->
   >> 18|   <% if (theme.favicon) { %>
      19|     <% if (theme.favicon.desktop) { %>
      20|     <% if (theme.gravatar.email && theme.favicon.desktop.gravatar) { %>
      21|       <link rel="shortcut icon" href="<%= gravatar(theme.gravatar.email, 16) %>">
  
  Cannot read properties of undefined (reading 'favicon')
      at eval ("/Users/an/Documents/Hexo_project/test/themes/hyde/layout/_partial/head.ejs":27:18)
      at head (/Users/an/Documents/Hexo_project/test/node_modules/ejs/lib/ejs.js:692:17)
      at _View._compiledSync (/Users/an/Documents/Hexo_project/test/node_modules/hexo/lib/theme/view.js:132:24)
      at _View.renderSync (/Users/an/Documents/Hexo_project/test/node_modules/hexo/lib/theme/view.js:59:25)
      at Object.partial (/Users/an/Documents/Hexo_project/test/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
      at eval ("/Users/an/Documents/Hexo_project/test/themes/hyde/layout/layout.ejs":12:17)
      at layout (/Users/an/Documents/Hexo_project/test/node_modules/ejs/lib/ejs.js:692:17)
      at _View._compiled (/Users/an/Documents/Hexo_project/test/node_modules/hexo/lib/theme/view.js:136:50)
      at _View.render (/Users/an/Documents/Hexo_project/test/node_modules/hexo/lib/theme/view.js:39:17)
      at /Users/an/Documents/Hexo_project/test/node_modules/hexo/lib/theme/view.js:51:25
      at tryCatcher (/Users/an/Documents/Hexo_project/test/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/an/Documents/Hexo_project/test/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/an/Documents/Hexo_project/test/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/an/Documents/Hexo_project/test/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/an/Documents/Hexo_project/test/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/an/Documents/Hexo_project/test/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/an/Documents/Hexo_project/test/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/an/Documents/Hexo_project/test/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/an/Documents/Hexo_project/test/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (node:internal/timers:464:21) {
    path: '/Users/an/Documents/Hexo_project/test/themes/hyde/layout/layout.ejs'
  }
} Render HTML failed: index.html
```

**Comment by jue89** [comment]
Oh, this theme is pretty old :D

What Hexo version are you using? `npm ls` may help you to find out.
